# Posts schema

# --- !Ups

CREATE TABLE POSTS(
  ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  SUBJECT VARCHAR  NOT NULL,
  CONTENT TEXT,
  USER_ID BIGINT NOT NULL,
  CONSTRAINT USER_FK foreign key (USER_ID) REFERENCES USERS(ID)
)

# --- !Downs

DROP TABLE POSTS
