# Posts schema

# --- !Ups

CREATE TABLE COMMENTS (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  USER_ID BIGINT NOT NULL,
  POST_ID BIGINT NOT NULL,
  CONSTRAINT USER_FK2 foreign key (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT POST_FK foreign key (POST_ID) REFERENCES POSTS(ID)
)

# -- !Downs
DROP COMMENTS
